# Sets up the dev environment (very obviously not for production)

version: "3"

services:
  db:
    image: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./create-multiple-postgresql-databases.sh:/docker-entrypoint-initdb.d/create-multiple-postgresql-databases.sh
    environment:
      # This also annoyingly creates a DB called doxa-dev (because of the username) and disabling it seems to cause an error.
      - POSTGRES_MULTIPLE_DATABASES=autha,doxa
      - POSTGRES_USER=doxa-dev
      - POSTGRES_PASSWORD=doxa-dev
    ports:
      - 5432:5432
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=doxa
      - RABBITMQ_DEFAULT_PASSWORD=doxa-dev
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
      - rabbitmq_log:/var/log/rabbitmq
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - 5050:80
    volumes:
      - pgadmin:/var/lib/pgadmin
  redis:
    image: bitnami/redis:6.2
    environment:
      - REDIS_PASSWORD=doxa-dev
    volumes:
      - redis:/bitnami/redis/data
    ports:
      - 6379:6379
  autha:
    image: ghcr.io/louisdewar/autha:production
    environment:
      - DATABASE_URL=postgres://doxa-dev:doxa-dev@db/autha
      - REDIS_URL=redis://:doxa-dev@redis:6379/1
    volumes:
      - ./dev_realm_config.toml:/app/config.toml
    depends_on:
      - redis
      - db
    ports:
      - 3002:8080


volumes:
  pg_data:
  rabbitmq_data:
  rabbitmq_log:
  pgadmin:
  redis:
